# Please read the https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta before you set up.
#
# These placeholders can be used in the chat format settings:
#
#  {message} - The chat message.
#  {name} - The player's name.
#  {displayname} - The player's display name or nickname.
#  {world} - The name of the player's current world.
#
#     Available using LuckPerms and Vault/VaultUnlocked:
#  {prefix} - The player's highest priority prefix.
#  {suffix} - The player's highest priority suffix.
#  {prefixes} - The player's prefixes sorted by the highest priority.
#  {suffixes} - The player's suffixes sorted by the highest priority.
#  {group} - The player's primary group.
#
#    Only LuckPerms:
#  {username-color} - The player's or the group's username color.
#  {message-color} - The player's or the group's message color.

# For more setting options, visit: https://github.com/SyntaxDevTeam/FormatterX/wiki

# Chat format settings
chat:
  defaultFormat: "{prefix}{username-color}{name}&r: {message-color}{message}"
  private-message:
    send: "&7[&aMe -> {receiver}&7] &r{message}"
    received: "&7[{sender} -> Me&7] &r{message}"
  group-formats: # Set the format per group.
  # Note: Option for more advanced users. Remove comments to run.
  #  default: "[default] {name}&r: {message}"
  #  moderator: "[moderator] {name}&r: {message}"
  #  admin: "[admin] {name}&r: {message}"
  #  owner: "[owner] {name}&r: {message}"
  prefixes_separator: " "
  suffixes_separator: " "
  mention-sound: "entity_experience_orb_pickup" # Sound played when a player is mentioned in chat. Possible values: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html



# Plugin language selection. Possible values:  EN, PL
# If you would like to add your own language file, please contact us on Discord (https://discord.gg/Zk6mxv7eMh).
language: "EN"

# Update check and auto-update settings
checkForUpdates: true
autoDownloadUpdates: false

# Debug mode set to true provides more detailed logs in the console
debug: false

# Should StatsCollector be enabled? Recommended setting: true
stats:
  enabled: true