name: FormatterX
main: pl.syntaxdevteam.formatter.FormatterX
version: ${version}
description: ${description}
api-version: '1.20'
folia-supported: true

authors: [SyntaxDevTeam]
website: https://github.com/SyntaxDevTeam/FormatterX
support:
  issues: https://github.com/SyntaxDevTeam/FormatterX/issues
  updates: https://github.com/SyntaxDevTeam/FormatterX/releases

localization:
  available: [en_US, pl_PL, fr_FR, es_ES, de_DE]
  default: en_US

loader: pl.syntaxdevteam.formatter.loader.SyntaxLoader
has-open-classloader: false
load: POSTWORLD

softdepend: [Folia]

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    MiniPlaceholders:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    VaultUnlocked:
      load: BEFORE
      required: false
    Essentials:
      load: BEFORE
      required: false

features:
  debug: true
  stats: true
  update-check: true
  auto-update: false